# Generated by Django 5.1.1 on 2024-10-05 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_todo_completed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="data_completed",
            new_name="date_completed",
        ),
    ]
